# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies (ignoring scripts to speed up install, if needed)
RUN npm install --ignore-scripts

# Copy all project files
COPY . .

# Build steps if necessary (this project does not require a build step, entry is in src/index.js)

# Expose port if MCP server listens on a specific port (not needed for stdio based MCP)

# Command to run the server (entrypoint via bin from package.json)
CMD ["node", "src/index.js"]
